DEV-32951 - add FieldsNamesSignatureProcessor
logzio/sawmill pull request #305
Opened 2022-07-18 13:29 UTC by ronshay

2022-07-24 11:13 UTC, ronshay commented on sawmill-core/src/main/java/io/logz/sawmill/processors/DocSignatureProcessor.java
> +    private final String DOC_SIGNATURE_FIELD = "logzio_doc_signature";
move field name to config

2022-07-24 11:22 UTC, ronshay commented on sawmill-core/src/main/java/io/logz/sawmill/processors/DocSignatureProcessor.java
> +            return ProcessResult.failure("signature is empty, SignatureMode: " + signatureMode);
consider

2022-07-24 11:45 UTC, ronshay commented on sawmill-core/src/main/java/io/logz/sawmill/processors/DocSignatureProcessor.java
> +    public static class Configuration implements Processor.Configuration {
add validation

2022-07-24 11:53 UTC, ronshay commented on sawmill-core/src/main/java/io/logz/sawmill/processors/DocSignatureProcessor.java
> +        return values.isEmpty() ? "" : JsonUtils.toJsonString(values);
redundant json

2022-07-24 11:56 UTC, ronshay commented on sawmill-core/src/main/java/io/logz/sawmill/processors/DocSignatureProcessor.java
> +    private Set<String> extractFieldsNames(Doc doc) throws InterruptedException {
rename

2022-07-24 12:13 UTC, AvishayHirsh requested changes

2022-07-24 12:13 UTC, AvishayHirsh commented on sawmill-core/src/main/java/io/logz/sawmill/processors/DocSignatureProcessor.java
> +    public void extractFieldsNames(Object object, String key, Set<String> fields) throws InterruptedException {
rename to parent

2022-07-24 12:13 UTC, AvishayHirsh commented on sawmill-core/src/main/java/io/logz/sawmill/processors/DocSignatureProcessor.java
> +                                new StringBuilder(key).append('.').append(entry.getKey()).toString() : entry.getKey(),
extract this line to separated line with meaningful var name

2022-07-24 12:13 UTC, AvishayHirsh commented on sawmill-core/src/main/java/io/logz/sawmill/processors/DocSignatureProcessor.java
> +                .filter(doc::hasField)
add test that nested field names is supported

2022-07-24 14:01 UTC, ronshay commented on sawmill-core/src/main/java/io/logz/sawmill/processors/DocSignatureProcessor.java
> +            return ProcessResult.failure("signature is empty, SignatureMode: " + signatureMode);
i think we should keep it.. consider a scenario where the algorithm is broken but does not throw an exception...

2022-07-25 10:55 UTC, AvishayHirsh commented
Add documentation for this processor

2022-07-25 11:18 UTC, AvishayHirsh commented on sawmill-core/src/main/java/io/logz/sawmill/processors/DocSignatureProcessor.java
> +    private void addSignatureField(Doc doc, List<String> signatureCollection) {
1] so we agree that it is better to use set hashcode 
2] we want to add a test that {a,b,c} signature is equals to {c,b,a}

2022-07-26 10:48 UTC, AvishayHirsh approved these changes
Great work

2022-07-26 10:48 UTC, AvishayHirsh commented on sawmill-core/src/main/java/io/logz/sawmill/processors/AddSignatureProcessor.java
> +    public void extractFieldsNames(Object object, String parentKey, Set<String> fields) throws InterruptedException {
change to private

2022-07-26 12:05 UTC, merged